# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-12 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20181012_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='age',
        ),
    ]
