# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-16 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20181015_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ucomment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ucomments', to='wall.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wall.Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wall.User'),
        ),
    ]
